name: build images
on:
    push:
        branches: ["master", "2.0", "next"]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Checkout
        uses: aliyun/acr-login@v1 # ä½¿ç”¨é˜¿é‡Œäº‘é•œåƒæœåŠ¡action
        with:
          persist-credentials: false
          login-server: registry.cn-hangzhou.aliyuncs.com # åŠ¡å¿…æ­£ç¡®å¡«å†™é•œåƒå®¹å™¨æœåŠ¡çš„ç™»å½•åœ°å€
          username: "${{ secrets.REGISTRY_USERNAME }}" # å¼•ç”¨GitHub repoè®¾ç½®çš„é•œåƒå®¹å™¨æœåŠ¡ç”¨æˆ·å
          password: "${{ secrets.REGISTRY_PASSWORD }}" # å¼•ç”¨GitHub repoè®¾ç½®çš„é•œåƒå®¹å™¨æœåŠ¡å¯†ç 
#      - name: Cache npm Repository
#        uses: actions/cache@v1
#        with:
#          path: ./node_modules
#          key: jetlinks-ui-pro-repository
      - name: Install ğŸ”§
        run: |
          set NODE_OPTIONS=-max_old_space_size=8096
          yarn install
          yarn run build
          cp -r dist docker/
          docker build -t registry.cn-hangzhou.aliyuncs.com/sky-devops/jetlinks/jetlinks-ui:$(node -p "require('./package.json').version") ./docker

      - name: Push Docker
        run: docker push registry.cn-hangzhou.aliyuncs.com/sky-devops/jetlinks/jetlinks-ui:$(node -p "require('./package.json').version")
